version: "3.1"

services:
  app:
    image: ambientum/php:7.3-nginx
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.backend=map"
      - "traefik.frontend.rule=Host:dragon-quiz.docker"
    environment:
      - FRAMEWORK=vanilla
    volumes:
      - .:/var/www/app
      - ./nginx/vanilla.conf:/etc/nginx/sites/vanilla.conf
    networks:
      - default
      - web

networks:
  web:
    external: true
